binop_separator = "Back"
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
hide_parse_errors = true
imports_layout = "Vertical"
match_block_trailing_comma = true
merge_derives = false
merge_imports = true
normalize_comments = true
overflow_delimited_expr = true
reorder_imports = false
use_field_init_shorthand = true
wrap_comments = true