[profile.release]
opt-level = 3
overflow-checks = true
lto = true

[workspace]
members = [
    "lib/flv",
    "lib/golomb",
    "lib/balance",
    "lib/transport",
    "lib/configure",
    "exchange",
    "publish",
    "pull"
]
