[package]
name = "turn-server"
version = "0.2.0"
edition = "2021"

[dependencies]
turn-rs = { path = "../turn", version = "1.0.1" }
clap = { version = "3", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.13"
async-trait = "0.1.52"
serde_json = "1.0.61"
env_logger = "0.8.2"
num_cpus = "1.13.0"
log = "0.4.11"
anyhow = "1.0"
axum = "0.6.1"
toml = "0.5.10"
