[package]
name = "turn"
version = "1.0.1"
edition = "2021"
authors = ["Mr.Panda <xivistudios@gmail.com>"]

[dependencies]
stun = { path = "../stun" }
tokio = { version = "1", features = ["sync"] }
async-trait = "0.1.60"
bytes = "1"
anyhow = "1.0"
rand = "0.7"
